# Generated by Django 5.0.1 on 2024-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_active_alter_destination_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
