# Generated by Django 5.0.1 on 2024-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
