# Generated by Django 5.0.1 on 2024-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_destination_name'),
        ),
    ]
