# Generated by Django 5.0.1 on 2024-01-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_gateways', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gateway', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payment_gateways.paymentgateway')),
                ('ticket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('ticket',), name='unique_payment_ticket'),
        ),
    ]
