# Generated by Django 5.0.1 on 2024-01-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriages', '0002_alter_carriage_active_alter_carriage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('business', models.BooleanField(db_index=True, default=False)),
                ('carriage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carriages.carriage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('carriage', 'number'), name='unique_seat_carriage_number'),
        ),
    ]
