# Generated by Django 5.0.1 on 2024-01-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sleeping', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('train', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
        ),
    ]
