# Generated by Django 5.0.1 on 2024-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='sleeping',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
