# Generated by Django 5.0.1 on 2024-01-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0006_alter_destination_active_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
            ],
        ),
    ]
