# Generated by Django 5.0.1 on 2024-01-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seats', '0001_initial'),
        ('trips', '0007_alter_trip_date_time_alter_trip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('price', models.FloatField(db_index=True)),
                ('taken', models.BooleanField(db_index=True, default=False)),
                ('seat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seats.seat')),
                ('trip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat', 'trip'), name='unique_ticket_seat_trip'),
        ),
    ]
