# Generated by Django 5.0.1 on 2024-01-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_id'),
        ('trips', '0003_remove_trip_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
    ]
