# Generated by Django 5.0.1 on 2024-01-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('trips', '0005_alter_trip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='arrival_date_time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_date_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('route', 'date_time'), name='unique_trip_route_date_time'),
        ),
    ]
